Repository dude613/avoda-fe, pull requests merged in 2025-04, with the labels that each got.

#35 Misc
  .github/workflows/ai-diff-review-openai.yml
  prreview1.py
  src/App.css
  src/components/Header.tsx
  src/components/ThemeToggle.tsx
  src/components/ui/button.tsx
  src/constants/Auth.ts
  src/constants/ForgotPassword.ts
  src/constants/Register.ts
  src/hooks/useTheme.ts
  src/pages/Dashboard/Dashboard.tsx
  src/pages/ForgotPassword/ResendForgotEmail.tsx
  src/pages/ForgotPassword/ResetNewPassword.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Login/index.tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Register/index.tsx
  src/ui/AuthInput.tsx
  tailwind.config.js
Labels: Review effort 3/5

#36 Add commit status reporting to PR Check Main workflow
  .github/workflows/pr-check-main.yml
  prreview1.py
Labels: Review effort 2/5

#38 updates for ui components and org onboarding
  src/App.tsx
  src/components/AddTeamMembers.tsx
  src/components/CircularLoading.tsx
  src/components/CreateOrganization .tsx
  src/components/Dashboard.tsx
  src/components/Header.tsx
  src/components/PasswordStrengthMeter.tsx
  src/components/ThemeToggle.tsx
  src/components/card-select.tsx
  src/components/drawer.tsx
  src/components/file-uploader.tsx
  src/components/form.tsx
  src/components/form/ErrorMessage.tsx
  src/components/form/email.tsx
  src/components/form/password.tsx
  src/components/toast.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/circular-loading.tsx
  src/components/ui/form-divider.tsx
  src/components/ui/icon-container.tsx
  src/components/ui/index.ts
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/navigation-link.tsx
  src/components/ui/progress-bar.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/constants/Auth.ts
  src/constants/Register.ts
  src/pages/Dashboard/Dashboard.tsx
  src/pages/ForgotPassword/ResendForgotEmail.tsx
  src/pages/ForgotPassword/ResetNewPassword.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/AddTeamMembers.tsx
  src/pages/Onboarding/CreateOrganization .tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Register/index.tsx
  src/ui/AuthInput.tsx
  src/ui/Card.tsx
  yarn.lock
Labels: Review effort 4/5

#41 Bug fix/orgainization onborading
  package.json
  src/App.tsx
  src/components/file-uploader.tsx
  src/constants/AddTeamMembers.ts
  src/pages/Login/index.tsx
  src/pages/Onboarding/AddTeamMembers.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Team/index.tsx
  yarn.lock
Labels: Review effort 4/5

#45 updated routes for team members
  src/Config.tsx
Labels: Review effort 1/5

#46 updated code for user profile section
  src/Config.tsx
  src/components/user-profile-drawer/UserProfile.tsx
  src/constants/Auth.ts
  src/constants/UserProfile.ts
  src/pages/Login/index.tsx
  src/pages/Onboarding/AddTeamMembers.tsx
  src/pages/Team/index.tsx
  src/service/api.tsx
Labels: Review effort 3/5

#47 Update React dependencies to version 19.1.0 and add Storybook log to …
  yarn.lock
Labels: Review effort 1/5

#49 fixed the type script error and ui issue
  src/components/card-select.tsx
  src/components/file-uploader.tsx
  src/components/form/email.tsx
  src/components/ui/card.tsx
  src/components/ui/navigation-link.tsx
  src/components/user-profile-drawer/UserProfile.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/AddTeamMembers.tsx
  src/pages/Register/index.tsx
  src/pages/Team/index.tsx
  src/redux/slice/OrganizationUser.tsx
  src/service/api.tsx
  src/util/Pagination.tsx
Labels: Review effort 4/5

#50 Update VerifyCode component with logging and navigation changes
  src/pages/Register/VerifyCode.tsx
Labels: Review effort 2/5

#52 Feat/avo 126 display individual user profile page
  src/pages/Register/VerifyCode.tsx
Labels: Review effort 1/5

#53 Storybook
  .github/workflows/build.yml
  package.json
  prreview1.py
Labels: Review effort 2/5

#56 Oluwadamilare321/avo 167 build robust sleek timer interface
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Config.tsx
  src/components/Timer/TimerDashboard.tsx
  src/components/Timer/TimerDisplay.tsx
  src/components/Timer/TimerHistory.tsx
  src/components/file-uploader.tsx
  src/components/ui/Badge.stories.ts
  src/components/ui/Label.stories.ts
  src/components/ui/Select.stories.tsx
  src/components/ui/Toast.stories.tsx
  src/components/ui/card-b.tsx
  src/components/ui/skeleton.tsx
  src/components/user-profile-drawer/UserProfile.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/AddTeamMembers.tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/index.tsx
  src/pages/Team/index.tsx
  src/pages/Timer/index.tsx
  src/redux/Store.tsx
  src/redux/slice/OrganizationUser.tsx
  src/redux/slice/Timer.tsx
  src/service/api.tsx
  src/service/socketService.tsx
  src/service/timerApi.tsx
  src/tests/Header.test.tsx
  src/types/TeamMember.ts
  src/util/Pagination.tsx
  tsconfig.json
Labels: Review effort 4/5

#55 Deployment fixes
  .github/workflows/build.yml
  .github/workflows/pr-check-main.yml
  .github/workflows/pr-check.yml
  package.json
  src/App.css
  src/components/file-uploader.tsx
  src/components/ui/Badge.stories.ts
  src/components/ui/Label.stories.ts
  src/components/ui/Select.stories.tsx
  src/components/ui/Toast.stories.tsx
  src/components/ui/input.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Debug.tsx
  src/pages/ForgotPassword/ResendForgotEmail.tsx
  src/pages/ForgotPassword/ResetNewPassword.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Home.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/AddTeamMembers.tsx
  src/pages/Onboarding/CreateOrganization .tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Register/index.tsx
  src/pages/Team/index.tsx
  src/pages/Unauthorized.tsx
  src/type.d.ts
  src/util/Pagination.tsx
  yarn.lock
Labels: Review effort 2/5

#68 Cleaned PR- oluwadamilare321/avo-167-build-robust-sleek-timer
  package.json
  pnpm-lock.yaml
  src/Config.tsx
  src/components/Header.tsx
  src/components/Timer/TimerControls.tsx
  src/components/Timer/TimerDashboard.tsx
  src/components/Timer/TimerDisplay.tsx
  src/components/ui/dialog.tsx
  src/components/ui/tooltip.tsx
  src/redux/slice/Timer.tsx
  src/service/socketService.tsx
  src/service/timerApi.tsx
Labels: Review effort 3/5

#67 Update-AI-to-use-agent
  commit-hygiene.md
  package.json
  prreview1.py
  yarn.lock
Labels: Review effort 3/5

#69 Oluwadamilare321/avo 204 users can filter and sort entries on the time logs table by date project client etc
  package.json
  pnpm-lock.yaml
  src/Config.tsx
  src/components/Timer/TimerControls.tsx
  src/components/Timer/TimerHistory.tsx
  src/components/filter/DateRangeFilter.tsx
  src/components/filter/FilterPanel.tsx
  src/components/filter/TextFilter.tsx
  src/components/filter/index.ts
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/components/ui/textarea.tsx
  src/redux/slice/Timer.tsx
  src/service/timerApi.tsx
Labels: Review effort 4/5

#72 Oluwadamilare321/avo 196 create full frontend for managing clients
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/filter/TextFilter.tsx
  src/components/ui/dropdown-menu.tsx
  src/pages/Clients/ClientForm.tsx
  src/pages/Clients/index.tsx
  src/redux/Store.tsx
  src/redux/slice/ClientSlice.tsx
  src/service/clientApi.tsx
  src/tests/Header.test.tsx
  src/types/Client.ts
Labels: Review effort 4/5
