Repository dude613/avoda-fe, pull requests merged in 2025-03, with the labels that each got.

#3 Chore/updates
  .gitignore
  components.json
  package.json
  postcss.config.js
  sample.env
  src/App.css
  src/App.tsx
  src/components/Header.tsx
  src/components/PasswordStrengthMeter.tsx
  src/components/form/PasswordWithStrength.tsx
  src/components/form/email.tsx
  src/components/form/otp.tsx
  src/components/form/password.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/constants/ForgotPassword.ts
  src/constants/Header.ts
  src/constants/Login.ts
  src/constants/Register.ts
  src/index.css
  src/lib/utils.ts
  src/pages/ForgotPassword/ResendForgotEmail.tsx
  src/pages/ForgotPassword/ResetNewPassword.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Login/index.tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Register/index.tsx
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: Review effort 3/5

#4 Chore/updates
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  package.json
  src/components/form/Email.stories.ts
  src/components/form/Otp.stories.ts
  src/components/form/Password.stories.ts
  src/components/form/PasswordWithStrength.stories.ts
  src/components/form/otp.tsx
  src/components/ui/Input.stories.ts
  vitest.workspace.ts
  yarn.lock
Labels: Review effort 2/5

#5 Main
  package.json
  src/App.css
  src/App.tsx
  src/components/AddTeamMembers.tsx
  src/components/CircularLoading.tsx
  src/components/CreateOrganization .tsx
  src/components/ProtectedRoute.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/ForgotPassword/ResetNewPassword.tsx
  src/pages/Login/index.tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Register/index.tsx
  src/service/api.tsx
  src/ui/Button.tsx
  src/ui/FileUploader.tsx
  src/ui/Input.tsx
  tailwind.config.js
  yarn.lock
Labels: Review effort 4/5

#16 Chore/sentry
  src/App.tsx
  src/main.tsx
  yarn.lock
Labels: Review effort 2/5

#20 Fixed constant files issue
  src/components/PasswordStrengthMeter.tsx
  src/main.tsx
  src/pages/Login/index.tsx
  yarn.lock
Labels: Review effort 2/5

#27 Starting UI Improvements
  .github/workflows/ai-diff-review-openai.yml
  package.json
  prreview1.py
  src/App.css
  src/components/AddTeamMembers.tsx
  src/components/CreateOrganization .tsx
  src/components/PasswordStrengthMeter.tsx
  src/components/form/PasswordWithStrength.tsx
  src/components/form/email.tsx
  src/components/form/password.tsx
  src/components/toast.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/constants/Auth.ts
  src/constants/Login.ts
  src/hooks/use-toast.ts
  src/main.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/ForgotPassword/ResendForgotEmail.tsx
  src/pages/ForgotPassword/ResetNewPassword.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Login/index.tsx
  src/pages/Register/SetPassword.tsx
  src/pages/Register/VerifyCode.tsx
  src/pages/Register/index.tsx
  src/tests/Login.test.tsx
  src/ui/AuthInput.tsx
  src/ui/Button.tsx
  src/ui/Card.tsx
  src/ui/FileUploader.tsx
  src/ui/Input.tsx
  src/util/Pagination.tsx
  yarn.lock
Labels: Review effort 3/5

#29 Update UI styling misc
  index.html
  src/components/ui/input.tsx
  src/pages/Login/index.tsx
  src/ui/AuthInput.tsx
Labels: Review effort 1/5
